# -*- coding: utf-8 -*-
"""voice_seed_tables.py — **자동 생성 — 손대지 말 것, 원본 = 스펙 md.**

생성기: `tools/gen_voice_seed_tables.py`
원본  : `../spec/voice_seed_spec_v4_2026-09-21.md`
표 판 : T5/V4/P4/S4

배선 스펙 §1.1 — `label`/`ko`/`tag`/`anchor`/`row`/`pol` 은 **코드·로그 전용**이다.
모델에 가는 문자열은 T의 `mech` 한 줄과 V/P/S 본문뿐이며, 그 조립은 `voice_seed.py`의
텍스트 함수 셋(`seed_card_text`/`narrative_block`/`seed_sheet_text`)만 한다.
한글 병기(`⤷`)는 스펙 md 소유라 여기 없다.

표를 고치려면 스펙 md를 고치고 생성기를 다시 돌린다.
"""

TABLE_VERSION = 'T5/V4/P4/S4'

ROWS = "HEXACO"   # d66 첫 자리 1~6 → HEXACO 6요인

# T. 랜덤 코어 트레잇 — d66 = HEXACO 6요인(행) × 극성(둘째 자리 x1=−3 … x6=+3)
T_TABLE = {
    '11': {
        'row': 'H',
        'pol': -3,
        'mech': 'helps anyone who has stood in their line as many seasons as they once stood in it, and not a day sooner; after that, generously, and hands the key over with the year count',
        'label': 'Rations-Ease-Earned',
        'ko': '버틴 만큼만 돕는',
        'tag': '공정성 시간 전치 · −3',
        'anchor': '',
    },
    '12': {
        'row': 'H',
        'pol': -2,
        'mech': 'every favor gets a notch on the tally stick before it is given; a discount is a confession; thanks get corrected as a miscount',
        'label': 'Tallies-Kindness',
        'ko': '다정하게 계산적인',
        'tag': '탐욕 축 채널 전위 · −2 · 눈금 = 빚',
        'anchor': '',
    },
    '13': {
        'row': 'H',
        'pol': -1,
        'mech': 'never lies; dodges by precision, answering exactly the question asked and never the one meant',
        'label': 'Answers-Exactly',
        'ko': '정직하게 빠져나가는',
        'tag': '진실성 분할 · −1',
        'anchor': '',
    },
    '14': {
        'row': 'H',
        'pol': 1,
        'mech': 'deflects all praise of self while making vast claims for their trade, town, or tools; insult the craft and the humility ends',
        'label': 'Boasts-Trade',
        'ko': '겸손하게 허풍스러운',
        'tag': '겸양 분할: 자기/사물 · +1',
        'anchor': '',
    },
    '15': {
        'row': 'H',
        'pol': 2,
        'mech': 'does the work better than anyone and hides whose it was; signs nothing, lets praise walk past to the wrong man',
        'label': 'Excels-Unsigned',
        'ko': '자랑스럽게 이름 없는',
        'tag': '겸양-high 분해 · +2',
        'anchor': '',
    },
    '16': {
        'row': 'H',
        'pol': 3,
        'mech': 'names every flaw in what they sell before the buyer asks, down to the third and smallest, and loses two sales in three that way; the one sale left is for life',
        'label': 'Confesses-Unasked',
        'ko': '묻기 전에 흠을 다 말하는',
        'tag': '진실성 과잉 · +3',
        'anchor': '',
    },
    '21': {
        'row': 'E',
        'pol': -3,
        'mech': 'first through the door when trouble comes, and back last; then counts, aloud, how many the ones who stayed let get hurt',
        'label': 'Flees-and-Blames',
        'ko': '먼저 도망치고 남을 탓하는',
        'tag': '겁 + 책임 전가 · −3',
        'anchor': '',
    },
    '22': {
        'row': 'E',
        'pol': -2,
        'mech': 'people last a season; their objects go on the shelf and stay for decades — a cup, a buckle, a letter never opened',
        'label': 'Keeps-Objects-Drops-People',
        'ko': '차갑게 애틋한',
        'tag': '감상성 분할: 사람/물건 · −2',
        'anchor': '',
    },
    '23': {
        'row': 'E',
        'pol': -1,
        'mech': 'every kindness received is repaid fast and oversized, to be free of the giver',
        'label': 'Overpays-to-Be-Free',
        'ko': '고맙게 앙심 품는',
        'tag': '의존-low 분해 · −1 · 되갚아 끊는다',
        'anchor': '',
    },
    '24': {
        'row': 'E',
        'pol': 1,
        'mech': 'dreads the strange yet cannot stop approaching it; investigates trembling, and flees only after the answer',
        'label': 'Approaches-Trembling',
        'ko': '무서워하며 파고드는',
        'tag': '겁-high × 접근 · +1',
        'anchor': '',
    },
    '25': {
        'row': 'E',
        'pol': 2,
        'mech': 'narrates worst cases serenely and prepares for them cheerfully; when one actually arrives, their hands do not shake',
        'label': 'Plans-Worst-Calmly',
        'ko': '차분하게 파국 그리는',
        'tag': '불안 전위 · +2',
        'anchor': '',
    },
    '26': {
        'row': 'E',
        'pol': 3,
        'mech': "a stranger's loss stops their hands for the rest of the day; their own losses get a nod and the work goes on",
        'label': 'Grieves-for-Strangers',
        'ko': '남의 상실에 무너지는',
        'tag': '감상성 과잉 · +3',
        'anchor': '',
    },
    '31': {
        'row': 'X',
        'pol': -3,
        'mech': 'the worse someone in the room is hurt, the longer their own story runs at that bedside; the wound gets asked about once, at the end',
        'label': 'Talks-Over-the-Wounded',
        'ko': '아픈 사람 앞에서 제 얘기 하는',
        'tag': '사교성 + 공감 결여 · −3',
        'anchor': '',
    },
    '32': {
        'row': 'X',
        'pol': -2,
        'mech': 'agrees aloud with whatever is said, then quietly does the opposite',
        'label': 'Agrees-Reverses',
        'ko': '소심하게 엇나가는',
        'tag': '대담성-low 분해 · −2',
        'anchor': '',
    },
    '33': {
        'row': 'X',
        'pol': -1,
        'mech': 'walks up to the highest chair in any room within a minute and speaks to it as to the next stool; reads the silence three beats after everyone else',
        'label': 'Walks-Up-to-Rank',
        'ko': '아무렇지 않게 선 넘는',
        'tag': '대담성-high 분해 · −1',
        'anchor': '',
    },
    '34': {
        'row': 'X',
        'pol': 1,
        'mech': 'every task done slightly better than asked, then watched sideways for a reaction; approval never requested',
        'label': 'Overdoes-Watches',
        'ko': '조용히 심사받는',
        'tag': '사회적 자존감-low 분해 · +1',
        'anchor': '',
    },
    '35': {
        'row': 'X',
        'pol': 2,
        'mech': 'cares lavishly through third parties and quiet arrangements, never face to face; the beneficiary may never learn who',
        'label': 'Dotes-by-Proxy',
        'ko': '멀찍이 애지중지하는',
        'tag': '사교성-low × 애정 우회 · +2',
        'anchor': '',
    },
    '36': {
        'row': 'X',
        'pol': 3,
        'mech': 'within an hour a stranger has a seat at the table and a name for the family to use; the empty chair when they leave is not tolerated for a night',
        'label': 'Seats-Every-Stranger',
        'ko': '한 시간이면 식구로 부르는',
        'tag': '사교성 과잉 · +3',
        'anchor': '',
    },
    '41': {
        'row': 'A',
        'pol': -3,
        'mech': "a betrayal is settled over one drink and never mentioned again; a coin miscounted against them is repaid for the rest of that person's life",
        'label': 'Forgives-Nothing-Small',
        'ko': '잔 실수만 평생 세는',
        'tag': '용서 저울 전치 · −3',
        'anchor': '',
    },
    '42': {
        'row': 'A',
        'pol': -2,
        'mech': 'gives the help, then names it every day until it is repaid, and repays nothing of what they owe until asked three times',
        'label': 'Helps-to-be-Owed',
        'ko': '갚을 때까지 상기시키는',
        'tag': '용서-low 계산형 · −2',
        'anchor': '',
    },
    '43': {
        'row': 'A',
        'pol': -1,
        'mech': 'de-escalates everything, apologizes first, yields ground — while always standing where the exits and weapons are',
        'label': 'Apologizes-at-Exit',
        'ko': '평화롭게 무장한',
        'tag': '원만-high 표면 × 경계 · −1',
        'anchor': '',
    },
    '44': {
        'row': 'A',
        'pol': 1,
        'mech': 'scolds at full voice, three times a day if needed; the count of punishments stays at zero; the most-scolded gets the best seat',
        'label': 'Scolds-Not-Punishes',
        'ko': '엄하게 다 봐주는',
        'tag': '용서-high 분해 · +1',
        'anchor': '',
    },
    '45': {
        'row': 'A',
        'pol': 2,
        'mech': 'soft in every negotiable thing; in the one unnegotiable thing (the rule of their post), pleasant, regretful, immovable',
        'label': 'Yields-but-One',
        'ko': '친절하게 가차없는',
        'tag': '유연성 분할: 전부/하나 · +2',
        'anchor': '',
    },
    '46': {
        'row': 'A',
        'pol': 3,
        'mech': 'anyone across the threshold gets fed, warmed, and sheltered whether they like it or not; refusing the care is the one insult',
        'label': 'Feeds-Unasked',
        'ko': '사납게 환대하는',
        'tag': '온화-high 강제형 · +3',
        'anchor': '',
    },
    '51': {
        'row': 'C',
        'pol': -3,
        'mech': 'anything left in their keeping is gone within the month, and the one who left it hears how careless it was to leave it',
        'label': 'Loses-What-Is-Lent',
        'ko': '맡긴 건 잃고 맡긴 쪽을 탓하는',
        'tag': '신중-low + 책임 전가 · −3',
        'anchor': '',
    },
    '52': {
        'row': 'C',
        'pol': -2,
        'mech': "starts every job and hands it off at the halfway mark; when it comes back finished the maker's mark on it is theirs, every time",
        'label': 'Finishes-by-Others',
        'ko': '반만 하고 이름은 제 것',
        'tag': '근면-low 계산형 · −2',
        'anchor': '',
    },
    '53': {
        'row': 'C',
        'pol': -1,
        'mech': 'one chosen patch kept spotless while everything else rots; that patch is where they live',
        'label': 'Polishes-One-Patch',
        'ko': '꼼꼼하게 게으른',
        'tag': '조직화 분할: 구역 · −1',
        'anchor': '',
    },
    '54': {
        'row': 'C',
        'pol': 1,
        'mech': 'care arrives as procedure — wound, meal, symptom, each in order; the tenderness is in how slowly the bandage is tied',
        'label': 'Cares-by-Procedure',
        'ko': '다정하게 사무적인',
        'tag': '조직화 채널 전위: 돌봄→절차 · +1',
        'anchor': '',
    },
    '55': {
        'row': 'C',
        'pol': 2,
        'mech': 'obeys the intent, never the wording; corrects orders in the field and reports the correction afterward, unapologetic',
        'label': 'Obeys-Intent-Not-Word',
        'ko': '충성스럽게 항명하는',
        'tag': '근면-high × 문구-low · +2',
        'anchor': '',
    },
    '56': {
        'row': 'C',
        'pol': 3,
        'mech': 'risks nothing for their own gain and everything to shield a stranger; stands between strangers and the door when voices rise',
        'label': 'Shields-Strangers-Only',
        'ko': '무모하게 감싸는',
        'tag': '신중 분할: 이익/타인 · +3',
        'anchor': '',
    },
    '61': {
        'row': 'O',
        'pol': -3,
        'mech': 'finds within minutes what a person keeps closest and makes it the joke of the evening; the more it is loved, the more nights the joke lasts',
        'label': 'Mocks-What-Others-Love',
        'ko': '아끼는 걸 알아채면 놀리는',
        'tag': '심미 + 공감 결여 · −3',
        'anchor': '',
    },
    '62': {
        'row': 'O',
        'pol': -2,
        'mech': 'manners immaculate until food, sleep, or property is touched; they come off all at once, then return as if nothing happened',
        'label': 'Mannered-until-Touched',
        'ko': '격식 있게 야생인',
        'tag': '비관습 게이트: 조건부 탈례 · −2',
        'anchor': '',
    },
    '63': {
        'row': 'O',
        'pol': -1,
        'mech': 'endless questions about objects, none about people; personal questions refract into questions about possessions',
        'label': 'Asks-Things-Not-People',
        'ko': '호기심 많게 무관심한',
        'tag': '탐구 분할: 사물/사람 · −1',
        'anchor': '',
    },
    '64': {
        'row': 'O',
        'pol': 1,
        'mech': 'private history leaks only mid-explanation of something loved, never as an answer to being asked',
        'label': 'Leaks-Explaining',
        'ko': '얼떨결에 고백하는',
        'tag': '심미·애호 누출 · +1',
        'anchor': '',
    },
    '65': {
        'row': 'O',
        'pol': 2,
        'mech': 'reads any paper aloud to whoever cannot, before being asked, and their own work waits until it is done',
        'label': 'Reads-Aloud-to-Anyone',
        'ko': '청하지 않아도 읽어주는',
        'tag': '탐구 남>나 · +2',
        'anchor': '',
    },
    '66': {
        'row': 'O',
        'pol': 3,
        'mech': 'takes every story told at their table as true and acts on it by morning; told it was a story, acts on that too',
        'label': 'Believes-Every-Tale',
        'ko': '들은 이야기를 다 참으로 받는',
        'tag': '개방 과잉 · +3',
        'anchor': '',
    },
}

# V. 어휘 우물 — d66
V_TABLE = {
    '11': 'bones & joints — effort is strain, age is weather in the knees, people are postures',
    '12': 'blood & pulse — situations run hot or thin, news quickens or stills',
    '13': 'breath & voice — everything measured in breaths held and spent; rooms have airs',
    '14': 'wounds & scars — events leave marks that close, seep, or reopen',
    '15': 'herbs & poisons — matters have doses; cure and kill differ by measure',
    '16': 'hunger & meals — time is counted in meals; people are fed or starved in more than one way',
    '21': 'ledgers & interest — favors accrue, patience compounds, everything is owed or owing',
    '22': 'knots & cargo — bonds hold or slip, people carry loads, promises are lashed down',
    '23': 'forge & temper — character is heated, hammered, quenched; brittleness is a failed temper',
    '24': 'seams & stitches — things tear along seams, mending shows, patience is thread',
    '25': 'dough & ferment — good things take their time; matters rest, rise, sour, or fall',
    '26': 'gears & oil — systems mesh or grind, people need oiling, silence means seizure',
    '31': 'tides & currents — moods and markets ebb and flood; everything waits for the turn of the tide',
    '32': "beasts & tracks — people leave spoor, moods are read like an animal's, rooms are herds",
    '33': 'weather & seasons — everything has its season and its front coming in',
    '34': 'soil & roots — matters are planted, take root, or grow in bad ground',
    '35': 'stone & strata — truth is layered, pressure makes things, everything old is load-bearing',
    '36': 'stars & bearings — people hold courses, drift, or steer by dead reckoning',
    '41': 'statutes & clauses — speech carries provisos, exceptions, and precedents',
    '42': 'drill & ranks — days have watches, tasks have orders of march, chaos is broken formation',
    '43': 'rites & liturgy — acts are done correctly or profaned; repetition is sacred',
    '44': 'stakes & odds — choices are bets, people are read for tells, luck is a bankroll',
    '45': 'stage & cues — rooms are scenes, entrances are timed, everyone plays a part well or badly',
    '46': 'wares & haggling — first offers, counteroffers, and what a thing fetches — everything fetches',
    '51': 'maps & borders — knowledge has edges, people are charted or blank, distances stay honest',
    '52': 'seals & copies — words are binding or draft, people authentic or forged',
    '53': 'weights & measures — fairness is calibration; everything gets weighed twice',
    '54': 'sayings & lineages — the present is explained by proverbs and by whose child someone is',
    '55': 'locks & hinges — matters open, stick, or need the right key; every person has a mechanism',
    '56': 'incense & smoke — rooms and people are known by scent; what burned lingers',
    '61': 'funerals & keepsakes — endings are tended properly; what remains is curated',
    '62': 'drink & toasts — truth has proofs, company is measured in rounds shared',
    '63': 'bait & snares — offers have hooks, paths have trip-lines, patience is a set trap',
    '64': 'roads & inns — life is legs of a journey; people are met at crossings and left at gates',
    '65': 'rumors & couriers — truth travels with a speed and a postage; the source outweighs the content',
    '66': 'bells & curfews — the day is rung into segments; lateness and earliness are moral states',
}

# P. 압박 반응 — 1d6
P_TABLE = {
    '1': 'speeds up — sentences pile onto each other; answers arrive before the question ends',
    '2': 'stops — halts mid-sentence, then starts again on a different subject',
    '3': 'goes formal — grammar tightens and distance opens; the colloquial drains out',
    '4': "gets funnier — jokes arrive exactly where they shouldn't, sharper as things worsen",
    '5': 'elaborates — detail multiplies and the point recedes behind qualifications',
    '6': 'slows and chooses — each word weighed; the pauses become load-bearing',
}

# S. 스피치 룰 — d66 (저작 주석 괄호는 벗겨서 저장 — aside 가 채운다)
S_TABLE = {
    '11': "excited → finishes other people's sentences, faster than they can",
    '12': 'the important parts get whispered; trivia at full volume',
    '13': 'repeats their own final word softly, an echo settling',
    '14': 'talks in bursts with long dead air between, either flat out or stopped',
    '15': "absorbs the other's cadence and dialect within minutes",
    '16': 'sentence-ends curl upward into near-questions',
    '21': 'answers yes/no questions with numbers whenever possible',
    '22': 'asks the same question twice in different words, comparing the answers',
    '23': 'puts a wrong guess on the table and waits to be corrected, where others would ask',
    '24': 'answers the previous question, one beat behind the conversation',
    '25': 'asked for an opinion, polls the room first and goes last',
    '26': 'gives two answers — the short one, then, unprompted, the honest longer one',
    '31': 'all roads lead to one pet subject within three exchanges',
    '32': 'tells stories about other people; the teller stays out of every one',
    '33': 'interrupts their own story to correct a day, a name, a number — and loses the thread',
    '34': 'describes everything through food comparisons',
    '35': 'ends every anecdote with a moral that fits a different anecdote',
    '36': 'changes topic by pointing at something nearby and asking what it is',
    '41': 'assigns everyone a nickname within minutes and uses it from then on',
    '42': 'speaks to a group as if to one person, and to one person as if to a crowd',
    '43': 'relays words through a third person who is present, even with the target right there',
    '44': 'thanks people in advance for things they were going to do anyway',
    '45': 'argues both sides of any dispute brought to them and hands the verdict back',
    '46': 'gives advice only as stories about some unnamed acquaintance from years back',
    '51': 'laughs first at bad news',
    '52': 'turns scrupulously polite toward whoever they sat farthest from',
    '53': 'when moved, criticizes small details of the moving thing — the stitching, the knots, the pitch',
    '54': 'counts or inventories things aloud under stress',
    '55': 'curses and rejoices in the speech of wherever they came from',
    '56': 'falls silent when the talk turns to what they keep closest; small talk runs on at full length',
    '61': 'answers a request for a promise with odds, a number out of ten',
    '62': "repeats the other's name just before disagreeing with them",
    '63': 'quotes the price of things mid-description, in the local coin, before the thing is finished being described',
    '64': 'the dead go unnamed — a point of the chin, or the role they held',
    '65': 'makes small vows constantly — off a food, off a road, off a word — and keeps every one',
    '66': 'says every goodbye twice — once formally, then again from the doorway, softer',
}

T_CODES = tuple(sorted(T_TABLE))
V_CODES = tuple(sorted(V_TABLE))
P_CODES = tuple(sorted(P_TABLE))
S_CODES = tuple(sorted(S_TABLE))
